name: Continuous Integration

on:
  pull_request:
    branches:
      - main

jobs:
  automation-test-job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and test
        run: |
          npm install
          npm run ci:test
        env:
          VITE_BASE_API_URL: ${{ secrets.VITE_BASE_API_URL }}
      - name: upload cypress screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots
